// <auto-generated />
using System;
using CV_AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV_AI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250619024948_cv")]
    partial class cv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CV_AI.Models.Application", b =>
                {
                    b.Property<int>("ID_Application")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Application"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Candidate")
                        .HasColumnType("int");

                    b.Property<int>("ID_JobPost")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Application");

                    b.HasIndex("ID_Candidate");

                    b.HasIndex("ID_JobPost");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CV_AI.Models.Candidate", b =>
                {
                    b.Property<int>("ID_Candidate")
                        .HasColumnType("int");

                    b.Property<string>("CV_Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Candidate");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("CV_AI.Models.Category", b =>
                {
                    b.Property<int>("ID_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Category"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CV_AI.Models.Employer", b =>
                {
                    b.Property<int>("ID_Employer")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Employer");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("CV_AI.Models.JobPost", b =>
                {
                    b.Property<int>("ID_JobPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_JobPost"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Employer")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_JobPost");

                    b.HasIndex("ID_Employer");

                    b.ToTable("JobPosts");
                });

            modelBuilder.Entity("CV_AI.Models.JobPostCategory", b =>
                {
                    b.Property<int>("ID_JobPost")
                        .HasColumnType("int");

                    b.Property<int>("ID_Category")
                        .HasColumnType("int");

                    b.HasKey("ID_JobPost", "ID_Category");

                    b.HasIndex("ID_Category");

                    b.ToTable("JobPostCategories");
                });

            modelBuilder.Entity("CV_AI.Models.SavedJob", b =>
                {
                    b.Property<int>("ID_Candidate")
                        .HasColumnType("int");

                    b.Property<int>("ID_JobPost")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Candidate", "ID_JobPost");

                    b.HasIndex("ID_JobPost");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("CV_AI.Models.User", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_User"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CV_AI.Models.Application", b =>
                {
                    b.HasOne("CV_AI.Models.Candidate", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("ID_Candidate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CV_AI.Models.JobPost", "JobPost")
                        .WithMany("Applications")
                        .HasForeignKey("ID_JobPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("CV_AI.Models.Candidate", b =>
                {
                    b.HasOne("CV_AI.Models.User", "User")
                        .WithOne("Candidate")
                        .HasForeignKey("CV_AI.Models.Candidate", "ID_Candidate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_AI.Models.Employer", b =>
                {
                    b.HasOne("CV_AI.Models.User", "User")
                        .WithOne("Employer")
                        .HasForeignKey("CV_AI.Models.Employer", "ID_Employer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CV_AI.Models.JobPost", b =>
                {
                    b.HasOne("CV_AI.Models.Employer", "Employer")
                        .WithMany("JobPosts")
                        .HasForeignKey("ID_Employer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("CV_AI.Models.JobPostCategory", b =>
                {
                    b.HasOne("CV_AI.Models.Category", "Category")
                        .WithMany("JobPostCategories")
                        .HasForeignKey("ID_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CV_AI.Models.JobPost", "JobPost")
                        .WithMany("JobPostCategories")
                        .HasForeignKey("ID_JobPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("CV_AI.Models.SavedJob", b =>
                {
                    b.HasOne("CV_AI.Models.Candidate", "Candidate")
                        .WithMany("SavedJobs")
                        .HasForeignKey("ID_Candidate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV_AI.Models.JobPost", "JobPost")
                        .WithMany("SavedJobs")
                        .HasForeignKey("ID_JobPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("CV_AI.Models.Candidate", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("CV_AI.Models.Category", b =>
                {
                    b.Navigation("JobPostCategories");
                });

            modelBuilder.Entity("CV_AI.Models.Employer", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("CV_AI.Models.JobPost", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobPostCategories");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("CV_AI.Models.User", b =>
                {
                    b.Navigation("Candidate");

                    b.Navigation("Employer");
                });
#pragma warning restore 612, 618
        }
    }
}
